version: '3.7'

x-consul: &consul
  image: hashicorp/consul:${CONSUL_VERSION:-1.11.2}
  restart: always
  networks:
  - consul

services:
  traefik:
    image: traefik:${TRAEFIK_VERSION:-v2.10}
    command:
    - "--log.level=DEBUG"
    - "--api.insecure=true"
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"
    - "--entrypoints.web.address=:80"
    - "--api.dashboard=true"
    - "--api=true"
    #- "--providers.consul.endpoints=consul-server-1:8500"
    ports:
    - "80:80"
    - "8080:8080"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
    - consul
  #
  ##
  #
  consul-server-1:
    <<: *consul
    volumes:
    - "consul-data-1:/consul/data:Z"
    - "./consul/consul-server.hcl:/config/config.hcl:ro"
    command: "agent -config-file=/config/config.hcl"
    ports:
    - "8500:8500"
    - "8600:8600/tcp"
    - "8600:8600/udp"
    labels:
    - traefik.enable=true
    - traefik.http.routers.consul-server-1.rule=Host(`consul.local.gd`)
    - traefik.http.services.consul-server-1.loadbalancer.server.port=8500

  consul-server-2:
    <<: *consul
    command: "agent -config-file=/config/config.hcl -join consul-server-1"
    volumes:
    - "consul-data-2:/consul/data:Z"
    - "./consul/consul-server.hcl:/config/config.hcl:ro"

  consul-server-3:
    <<: *consul
    command: "agent -config-file=/config/config.hcl -join consul-server-1"
    volumes:
    - "consul-data-3:/consul/data:Z"
    - "./consul/consul-server.hcl:/config/config.hcl:ro"

  #whoami:
  #  image: "traefik/whoami"
  #  container_name: "simple-service"
  #  labels:
  #    - "traefik.enable=true"
  #    - "traefik.http.routers.whoami1.rule=Host(`whoami.demostrativo.com`)"
  #    - "traefik.http.routers.whoami1.entrypoints=web"

  #consul-server-2:
  #  image: hashicorp/consul:${CONSUL_VERSION:-1.11.2}
  #  container_name: consul-server2
  #  restart: always
  #  volumes:
  #  #- ./server2.json:/consul/config/server.json:ro
  #  - ./certs/:/consul/config/certs/:ro
  #  networks:
  #  - consul
  #  command: "agent -bootstrap-expect=3"
  #
  #consul-server-3:
  #  image: hashicorp/consul:${CONSUL_VERSION:-1.11.2}
  #  container_name: consul-server3
  #  restart: always
  #  volumes:
  #  #- ./server3.json:/consul/config/server.json:ro
  #  - ./certs/:/consul/config/certs/:ro
  #  networks:
  #  - consul
  #  command: "agent -bootstrap-expect=3"
  #
  ##
  #
  #consul-client:
  #  image: hashicorp/consul:${CONSUL_VERSION:-1.11.2}
  #  container_name: consul-client
  #  restart: always
  #  volumes:
  #  - ./client.json:/consul/config/client.json:ro
  #  - ./certs/:/consul/config/certs/:ro
  #  networks:
  #    - consul
  #  command: "agent"

networks:
  consul:
    driver: bridge

volumes:
  consul-data-1:
  consul-data-2:
  consul-data-3:
